apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}-keys-secret
  namespace: {{ include "aws-ecr-creds.namespace" . | quote }}
  labels:
{{ include "aws-ecr-creds.labels" . | indent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc | quote }}
