{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-ecr-creds.serviceAccountName" . }}
  namespace: {{ include "aws-ecr-creds.namespace" . | quote }}
  labels:
{{ include "aws-ecr-creds.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-ecr-creds.serviceAccountName" . }}
  labels:
{{ include "aws-ecr-creds.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ecr-creds.serviceAccountName" . }}
    namespace: {{ include "aws-ecr-creds.namespace" . | quote }}
{{ end }}
